/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ProductList {}
}

declare global {


  interface HTMLProductListElement extends Components.ProductList, HTMLStencilElement {}
  var HTMLProductListElement: {
    prototype: HTMLProductListElement;
    new (): HTMLProductListElement;
  };
  interface HTMLElementTagNameMap {
    'product-list': HTMLProductListElement;
  }
}

declare namespace LocalJSX {
  interface ProductList extends JSXBase.HTMLAttributes<HTMLProductListElement> {}

  interface IntrinsicElements {
    'product-list': ProductList;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


