/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ProductCheckout {
    'itemId': number;
  }
}

declare global {


  interface HTMLProductCheckoutElement extends Components.ProductCheckout, HTMLStencilElement {}
  var HTMLProductCheckoutElement: {
    prototype: HTMLProductCheckoutElement;
    new (): HTMLProductCheckoutElement;
  };
  interface HTMLElementTagNameMap {
    'product-checkout': HTMLProductCheckoutElement;
  }
}

declare namespace LocalJSX {
  interface ProductCheckout extends JSXBase.HTMLAttributes<HTMLProductCheckoutElement> {
    'itemId'?: number;
  }

  interface IntrinsicElements {
    'product-checkout': ProductCheckout;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


